Glossary updated with SORMAS Dashboard
hzi-braunschweig/SORMAS-Glossary pull request #14
Opened 2020-11-24 20:09 UTC by BasilKaburi

2020-11-25 14:36 UTC, JonasCir commented
@BasilKaburi Thank you very much! Please introduce line breaks to make review easier! Thanks :)

2020-11-25 14:37 UTC, JonasCir requested changes

2020-11-25 14:37 UTC, JonasCir commented on SORMAS DASHBOARD.md
> +Epidemiologic dashboards are digital innovations for realtime and periodic concurrent visualization of multiple streams of related data for purposes of surveillance and outbreak management. By these
Please split this into several lines

2020-11-25 14:37 UTC, JonasCir commented on SORMAS DASHBOARD.md
> +The SORMAS dashboard is the default interface/entity on logging onto SORMAS. The SORMAS dashboard has two sections viz. surveillance and contacts; each displayed at a time. These are represented by t
same

2020-11-25 14:37 UTC, JonasCir commented on SORMAS DASHBOARD.md
> +The Surveillance dashboard has two sections. The first section displays summary information on counts of each infectious disease for specified times or periods. This is accompanied by graphical displ
same

2020-11-25 14:37 UTC, JonasCir commented on SORMAS DASHBOARD.md
> +The contact dashboard displays summary information of individuals reported to have come into contact with suspected or confirmed cases of an a given infectious disease. For a selceted disease of inte
same

2021-03-10 15:13 UTC, bernardsilenou commented
All is fine as I can see on the main link. I would close it for now

2021-03-10 15:13 UTC, closed without merging