Add files via upload
hzi-braunschweig/SORMAS-Glossary pull request #19
Opened 2020-12-11 00:47 UTC by BasilKaburi

I have uploaded a revised version of the dashboard directory of the SORMAS glossary.

2020-12-11 17:48 UTC, JonasCir commented
@bernardsilenou 
```
git clone
git checkout  BasilKaburi-patch-2
# Then you make your edits
git add + git commit
git push
# Request review and I merge
```

2020-12-17 01:49 UTC, bernardsilenou approved these changes

2020-12-17 01:53 UTC, bernardsilenou requested changes
The file has a new version, thus no need to review

2020-12-17 01:56 UTC, bernardsilenou approved these changes

2020-12-17 02:00 UTC, merged

2020-12-17 02:00 UTC, bernardsilenou commented
@JonasCir 
I deleted the other files and merged the file name DASHBOARD_DIRECTORY
please have a look if all is fine.